version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: taskflow_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: taskflow

volumes:
  mongo_data: